name: "pipeline_cripto"
version: "1.0.0"
config-version: 2

profile: "pipeline_cripto"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  pipeline_cripto:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
