pipeline_cripto:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET_ANALYTICS', 'cripto_analytics') }}"
      location: "{{ env_var('GCP_LOCATION', 'southamerica-east1') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
